services:
  - type: web
    name: gesapp-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://zerveck:n74SNV0Gm5i226yc@clustserverkainos.uhwrs.mongodb.net/gesapp?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: n74SNV0Gm5i226yc
      - key: JWT_EXPIRES_IN
        value: 24h